import re


ATEST_TIME = re.compile(r'sfn:(\d+), sf:(\d+)')
BANDWIDTH = re.compile(r'dlBandwidth')
BBUEREF = re.compile(r'bbUeRef')
CELLID = re.compile(r'cellId')
CFR_CRC_FLAG =re.compile(r'cfrCrcFlag')
CFR_FORMAT = re.compile(r'cfrFormat')
CFR_LENGTH = re.compile(r'cfrLength')
CFR_VALID = re.compile(r'cfrValid')
CFR_WDIGIT = re.compile(r'cfr \d+,')
GET_BBUEREF_EQL = re.compile(r'bbUeRef=(\w+)')
GET_CCES_EQL = re.compile(r'ofCce=(\d+)')
GET_CELLID_EQL = re.compile(r'cellId=(\d+)')
GET_CFR = re.compile(r'cfr (\d+)')
GET_DUID_EQL = re.compile(r'DuId=(\d+)')
GET_FIRST_DIGITS = re.compile(r'(\d+)')
GET_FIRST_DIGIT = re.compile(r'(\d)')
GET_HARQ_IDX_EQL = re.compile(r'HARQ idx=(\d+)')
GET_LAYERS_EQL = re.compile(r'Layer=(\d+)')
GET_MCS_2CW_EQL = re.compile(r'mcs={(\d+) (\d+)')
GET_NR_CW_EQL = re.compile(r'fCw=(\d+)')
GET_PRBS_EQL = re.compile(r'Prbs={(\d+)')
GET_RNTI_EQL = re.compile(r'rnti=(\d+)')
GET_SF = re.compile(r'sf:(\d).')
GET_SF_MICRO_SEC = re.compile(r'sf:\d.(\d+)')
GET_SFN = re.compile(r'sfn:(\d+)')
GET_SUBFRAME_NR_EQL = re.compile(r'subframeNr=(\d+)')
GET_SWAPFLAG_EQL = re.compile(r'SwapFlag=(\d+)')
GET_TBS_2CW_EQL = re.compile(r'tbs={(\d+) (\d+)')
GET_REDUNDANCY_VER = re.compile(r'rv={(\d) (\d)')
GLOBAL_TIME = re.compile(r'\[\d+\-(\d+)\-(\d+) (\d+):(\d+):(\d+).(\d+)')
HARQ_FDBK_IND = re.compile(r'detectedHarqIndication')
HARQ_PROC_ID = re.compile(r'dlHarqProcessId')
HARQ_VALID = re.compile(r'dlHarqValid')
IS_DTX = re.compile(r'isDtx \d,')
NR_PUCCH_RPT = re.compile(r'nrOfPucchReports')
NR_PUSCH_RPT = re.compile(r'nrOfPuschReports')
NR_TB = re.compile(r'nrOfTb')
PUCCH_RPT_LIST = re.compile(r'pucchReportList')
PUSCH_RPT_LIST = re.compile(r'puschReportList')
RANK = re.compile(r'ri ')
RANK_BIT_WIDTH = re.compile(r'riBitWidth')
SUBFRAME_NO = re.compile(r'subFrameNo')
SRS_RPT_LIST = re.compile(r'srsReportList')
HAS_DIGIT = re.compile(r'\d')